### ISSUE TITLE
doc on resource limits for Envoy container

### ISSUE THREAD

**Issue by saiteja313** [awsdocs/aws-app-mesh-user-guide#22]
Checking the example [1] Envoy manifest for EKS, Manifest is configured to use following resource requests for Envoy side car container,

```
    Requests:
      cpu:     10m
      memory:  32Mi
```

However, there is no documentation for CPU/Memory requests/limits for Envoy container running on ECS.

It would be great to list performance test results for Envoy container (integrated with AppMesh) when deploy on
1. EKS
2. ECS

Something like below,

- *For `x` TPS, envoy container uses `y` CPU, `z` Memory on ECS*
- *For `x1` TPS, envoy container uses `y1` CPU, `z1` Memory on EKS*

References:
---
[1] https://github.com/awsdocs/aws-app-mesh-user-guide/blob/master/doc_source/mesh-k8s-integration.md#step-3-create-or-update-services

**Comment by bigdefect** [comment]
Hey there, thanks for the request. I don't have administrative access to this repo, but if you could transfer this over to https://github.com/aws/aws-app-mesh-roadmap I can get some eyes on it from the team.

**Comment by saiteja313** [comment]
[#248](https://github.com/aws/aws-app-mesh-roadmap/issues/248) @efe-selcuk

**Comment by jimdial-aws** [comment]
Closing this issue in this repo then.
