### ISSUE TITLE
1.13 Incompatible inject script referenced in user guide

### ISSUE THREAD

**Issue by geremyCohen** [awsdocs/aws-app-mesh-user-guide#6]
The AWS User Guide has the users run v0.1.4 of the sidecar inject script which doesn't work on EKS v1.13.

**Comment by jimdial-aws** [comment]
Sorry for the delayed reply. Thank you for bringing this to our attention. I've updated the version to 0.1.6 in the documentation. That version works with EKS 1.13. The update will publish later today. Thank you for using AWS App Mesh and Amazon EKS!
